### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by top-master** [ulearnpro/ulearn#3]
I had some hard time trying to get this working,
And it would be nice if something about "APP_KEY" could be appended to the installation instructions, like below:

---
After above, ensure that your "`.env`" file at least contains the empty key-option "`APP_KEY=`",
And run below to generate and set a key option in your "`.env`" configuration file:
```
php artisan key:generate
php artisan config:cache
```
---

Another problem was that the "`public/.htaccess`" file did not exist and I added one from another Laravel project, something like:
```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews -Indexes
    </IfModule>

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

**Comment by ulearnpro** [comment]
@top-master Thanks for your suggestion, Now I have added the .env and .htaccess file to the repo..

**Comment by ulearnpro** [comment]
Added .env and .htaccess files

**Comment by PWA-GouldA** [comment]
The current release has the `.htaccess` in the **wrong** folder. 

It needs to be moved from the application **root** (`/`) to the application's **public** folder (`/public/`).
